# Generated by Django 2.1 on 2019-07-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagePromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_promo', models.CharField(max_length=120)),
                ('Image_promo', models.ImageField(blank=True, help_text='Ukuran image 1920x960', null=True, upload_to='promosi', verbose_name='Promo Picture')),
            ],
        ),
        migrations.CreateModel(
            name='promosi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_promosi', models.CharField(max_length=250)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Pilih_Promosi', models.ManyToManyField(to='marketing.imagePromo')),
            ],
        ),
    ]
