# Generated by Django 2.2.6 on 2019-10-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20190916_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepromo',
            name='keterangan',
        ),
        migrations.AddField(
            model_name='imagepromo',
            name='link',
            field=models.CharField(choices=[('/product/detail/grand-amelia', 'amelia'), ('/product/detail/garden-asri', 'garden asri'), ('/product/detail/garden-cluster-kepanjen', 'Garden Cluster'), ('/product/detail/puri-taman-agung', 'PTA')], default=1, max_length=500),
            preserve_default=False,
        ),
    ]
