# Generated by Django 2.2.6 on 2019-10-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20191028_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepromo',
            name='link',
            field=models.CharField(blank=True, choices=[('/product/detail/grand-amelia', 'amelia'), ('/product/detail/garden-asri', 'garden asri'), ('/product/detail/garden-cluster-kepanjen', 'Garden Cluster'), ('/product/detail/puri-taman-agung', 'PTA')], max_length=500, null=True),
        ),
    ]
