# Generated by Django 2.2.7 on 2020-04-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20191028_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFrontpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_profile', models.CharField(blank=True, max_length=20, null=True)),
                ('banner_pc', models.ImageField(blank=True, null=True, upload_to='media')),
                ('banner_mobile', models.ImageField(blank=True, null=True, upload_to='media')),
                ('banner_midle', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='imagepromo',
            name='link',
            field=models.CharField(blank=True, choices=[('/product/detail/grand-amelia', 'amelia'), ('/product/detail/garden-asri', 'garden asri'), ('/product/detail/garden-cluster-kepanjen', 'Garden Cluster'), ('/product/detail/puri-taman-agung', 'PTA'), ('/product/detail/sativa-at-malang', 'SATIVA')], max_length=500, null=True),
        ),
    ]
