# Generated by Django 2.1 on 2019-07-13 00:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pengembangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi2', tinymce.models.HTMLField(verbose_name='Content')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='pengembangan pic')),
                ('kategori', models.CharField(choices=[('pengembangan', 'pengembangan'), ('pembangunan', 'pembangunan'), ('news', 'news')], max_length=250)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='perijinan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_artikel', models.CharField(blank=True, max_length=255)),
                ('Materi', tinymce.models.HTMLField(verbose_name='content')),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
