# Generated by Django 2.1 on 2019-10-14 16:52

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_album', models.CharField(max_length=50)),
                ('poster_album', models.ImageField(blank=True, upload_to='album/')),
                ('penerbit_musik', models.CharField(max_length=50)),
                ('tanggal_rilis', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AlbumMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artikel.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Musik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_musik', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pengembangan',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengembangan',
            name='isi2',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AddField(
            model_name='album',
            name='nama_musik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artikel.Musik'),
        ),
    ]
