# Generated by Django 2.2.6 on 2019-10-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_auto_20191014_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albummusic',
            name='nama_album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='AlbumMusic',
        ),
        migrations.DeleteModel(
            name='Musik',
        ),
    ]
