# Generated by Django 2.2.6 on 2019-10-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_auto_20191024_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengembangan',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
    ]
