# Generated by Django 2.2.6 on 2019-10-22 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ameneties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ameneties', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='kondisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('luas', models.IntegerField()),
                ('luas_bangunan', models.IntegerField()),
                ('k_tidur', models.IntegerField()),
                ('k_mandi', models.IntegerField()),
                ('garasi', models.CharField(choices=[('ada', 'ada'), ('tidak', 'tidak')], max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('map_point', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sewa', 'sewa'), ('jual', 'jual')], max_length=255)),
                ('tipe', models.CharField(choices=[('perumahan', 'perumahan'), ('kavling', 'kavling'), ('rumah', 'rumah')], max_length=255)),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='property')),
                ('foto_utama', models.ImageField(blank=True, null=True, upload_to='property')),
                ('deskripsi', tinymce.models.HTMLField(blank=True, verbose_name='content')),
                ('harga', models.FloatField()),
                ('Nominals', models.CharField(choices=[('Jt', 'Jt'), ('M', 'M')], default='M', max_length=50, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('terjual', models.BooleanField(default=False)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.kondisi')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(to='property.ameneties')),
            ],
        ),
        migrations.CreateModel(
            name='gallerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gambar', models.ImageField(blank=True, null=True, upload_to='property')),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('kirim_notifikasi', models.BooleanField(default=False)),
                ('Notlp', models.DecimalField(decimal_places=0, max_digits=12)),
                ('No_id', models.DecimalField(decimal_places=0, max_digits=15)),
                ('booking', models.BooleanField(default=False)),
                ('DP', models.BooleanField(default=False)),
                ('data_user', models.BooleanField(default=False)),
                ('prinsip', models.BooleanField(default=False)),
                ('proses_bangun', models.BooleanField(default=False)),
                ('realisasi', models.BooleanField(default=False)),
                ('bast', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
