# Generated by Django 2.2.6 on 2019-10-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='services',
            field=models.ManyToManyField(to='property.ameneties'),
        ),
    ]
