# Generated by Django 2.2.6 on 2019-10-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallerys',
        ),
    ]
