# Generated by Django 2.2.6 on 2019-11-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_delete_gallerys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='DP',
            new_name='data_ket_kerja',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='bast',
            new_name='data_kk',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='booking',
            new_name='data_ktp_istri',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='data_user',
            new_name='data_ktp_suami',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='prinsip',
            new_name='data_npwp',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='proses_bangun',
            new_name='data_rek',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='realisasi',
            new_name='data_slip_gaji',
        ),
        migrations.AddField(
            model_name='customer',
            name='Booking_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Jumlah_booking',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cara_bayar',
            field=models.CharField(blank=True, choices=[('KPR', 'KPR'), ('Tunai Keras', 'Tunai Keras'), ('InHouse', 'InHouse')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='data_surat_nikah',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='image_realisasi',
            field=models.ImageField(blank=True, null=True, upload_to='data user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='image_serah_terima',
            field=models.ImageField(blank=True, null=True, upload_to='data user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='jumlah_sp3k',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pembaruan_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='persetujuan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='persetujuan_image',
            field=models.ImageField(blank=True, null=True, upload_to='data user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tgl_persetujuan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tgl_persetujuan_prinsip',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tgl_realisasi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tgl_serah_terima',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tgl_sp3k',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='tipe',
            field=models.CharField(choices=[('perumahan', 'perumahan'), ('kavling', 'kavling'), ('rumah', 'rumah'), ('ruko', 'ruko')], max_length=255),
        ),
        migrations.CreateModel(
            name='uangmuka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True)),
                ('keterangan', models.CharField(max_length=255)),
                ('tgl_byr', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uang_muka', to='property.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProsesBangun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='data user')),
                ('tgl', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosesbangun', to='property.Customer')),
            ],
        ),
    ]
