# Generated by Django 2.2.6 on 2019-11-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20191112_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='persetujuan_image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tgl_persetujuan',
        ),
        migrations.AddField(
            model_name='customer',
            name='Bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
