# Generated by Django 2.2.7 on 2020-05-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200504_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='proyek',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
